### ISSUE TITLE
노래 검색 예외 사항들

### ISSUE THREAD

**Issue by alpha-src** [Foundy-LLC/p_lyric#40]
### 한국 가수를 영어로 검색해야 되는 문제 
아래 예시를 보면 `키드밀리` 로 검색하면 안뜨고 `Kid Milli` 로 검색해야됨
<img src="https://user-images.githubusercontent.com/54366260/130956433-55f15a21-6055-40ab-a1fa-adb52390f806.jpg" width="40%">

### 한국 노래가 영어로 번역돼서 나오는 경우
아래 예시는 `Genius` 에서 검색해야됨
<img src="https://user-images.githubusercontent.com/54366260/130956435-a7ca2718-bf70-4c2b-b0ec-51a300539505.jpg" width="40%">

### 가수명이 멜론에서 다른 경우
아래 예시는 `악동뮤지션`인데 멜론에서는 `AKMU` 또는 `악뮤` 로 검색해야됨
<img src="https://user-images.githubusercontent.com/54366260/130957080-a4d04e36-48a3-4a33-971c-4ca94a2a5798.jpg" width="40%">

### 가수명이 번역되어 검색이 안되는 경우
아래 예시는 `염따` 로 검색되어야 하는데 `YUMDDA` 로 검색함
`Genius` 검색을 통해 해결 가능
<img src="https://user-images.githubusercontent.com/54366260/130956441-1f09d25f-cd0c-4cd4-99fd-3dd0fbf17539.jpg" width="40%">

**Comment by alpha-src** [comment]
* #50 으로 문제 해결

**Comment by jja08111** [comment]
![image](https://user-images.githubusercontent.com/57604817/131962270-8d1a4b94-43f3-4aa4-90b7-4bc4957c281a.png)

**Comment by alpha-src** [comment]
#81 을 적용하여 어느 정도 해결함 
다만 genius 는 사이트 측 문제로 적용하지 않기로 함 😮‍💨
